version: '3.8'

services:
  yuna-database:
    container_name: yuna-database
    env_file:
      - .env
    image: mariadb:10.9
    ports:
      - "3306:3306"
    volumes:
        - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
        - yuna-network
    restart: always
    hostname: yuna-database

  yuna-bot:
    image: yuna-bot
    container_name: yuna-bot
    depends_on:
      - yuna-database
    networks:
      - yuna-network
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    restart: always
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@yuna-database:3306/${MYSQL_DATABASE}
    hostname: yuna-bot

networks:
    yuna-network:
      external: false
      name: yuna-network